version: '3'
services:
  mibackend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  mongo:
    container_name: mymongodb
    image: mongo:3.6.8
    ports:
      - '27018:27017'
